### PR TITLE
Fixes #252

### LINKED ISSUE #252: Incorrect autocomplete
@mcaceresb 	
I'm writing tests; finding bugs.

image

image

### PR DESCRIPTION
**Pull request by mcaceresb**
- [X] closes #252 
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by kylebarron** [comment]
Thanks

**Comment by kylebarron** [comment]
Any ideas for tests?

**Comment by kylebarron** [comment]
Like, I think I figured out how to run tests, but curious if you had ideas for issues that are helpful to test.

**Comment by mcaceresb** [comment]
Kind of; nothing automated. How are you running them?

**Comment by kylebarron** [comment]
let's move conversation to https://github.com/kylebarron/stata_kernel/pull/254

**Pull request merged**
