### PR TITLE
Some #delimit fixes

### PR DESCRIPTION
**Pull request by kylebarron**
This fixes:

- (Not a #delimit fix) Prevents completion when last token is a multiline comment
image
- Adds a magic named `%delimit` that prints the current delmiter
- Logs to the screen when the delimiter changes

### CODE REVIEW

**Comment by kylebarron** [comment]
See this branch for progress:
https://github.com/kylebarron/stata_kernel/tree/dev-two-lexers

Do you think performance would suffer by lexing twice?

Also I'm kinda just considering writing my own stack, which would be a learning experience for me.

**Comment by mcaceresb** [comment]
Two passes, one for comments one for parsing, is basically the conclusion I came to when trying to write a regex-based snippet to parse stata code.

> Do you think performance would suffer by lexing twice?

Probably not. That type of stuff will make performance suffer for pasting large text blocks. In those cases it seems acceptable for the parser to take its time.

For syntax highlighting this would be a big no no bc it would slow down text exiting, but that is not a concern here.

> Also I'm kinda just considering writing my own stack, which would be a learning experience for me.

Not sure what you mean.

**Comment by kylebarron** [comment]
- This now uses two separate lexers.
- It seems to solve the first two issues, while the last issues are log-file parsing related
- It also removes the code that prevented both images and text from being sent (I can't reproduce my issues in Hydrogen).

I'm editing the tests I wrote so that they pass this. @mcaceresb would you like to test it out?

**Comment by kylebarron** [comment]
Move this discussion to #70

**Pull request closed without merging**
