### PR TITLE
Fixes #389; copyright no longer wrapped in a tag

### LINKED ISSUE #389: %help magic chokes when parsing retrieved HTML
#### Problem description

When using the `%help` magic, the kernel throws an exception while (it looks like from the logs) trying to parse the HTML fetched from [stata.com/help.cgi](https://www.stata.com/help.cgi?oneway). This results in no output for any invocation of `%help` except the built-in `%help kernel` and `%help magics` commands.

#### Debugging log

[console_debug.log](https://github.com/kylebarron/stata_kernel/files/6371461/console_debug.log)

More saliently this is the python output from stderr of the jupyterlab process:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
yield gen.maybe_future(handler(stream, idents, msg))
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
value = future.result()
File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
yielded = ctx_run(next, result)
File "/opt/conda/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 536, in execute_request
self.do_execute(
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/kernel.py", line 110, in do_execute
code = self.magics.magic(code, self)
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/stata_magics.py", line 228, in magic
code = getattr(self, "magic_" + name)(code, kernel)
File "/opt/conda/lib/python3.8/site-packages/stata_kernel/stata_magics.py", line 633, in magic_help
soup.find('a', text='Copyright').find_parent("table").decompose()
AttributeError: 'NoneType' object has no attribute 'find_parent'
```

#### Expected Output

An inline rich-text help as described in the [stata_kernel manual](https://kylebarron.dev/stata_kernel/using_stata_kernel/magics/#help).

#### Other information

It looks from the error output that `stata_magics.py` is trying to parse the DOM tree for an `<a>` element containing the text 'Copyright', but rather than checking whether it found one, just assumes it is present—and then the call to `.find_parent()` is choking, because it’s not.

I am guessing that in a previous version of stata.com/help.cgi <ins>some portion of</ins> the HTML quoted below was wrapped in an `<a>` tag, and that it’s subsequently been rewritten. 

```html
<table border=0 cellpadding=2 cellspacing=0 width="100%">
<tr>
<td valign=top align=center>
<font face="arial,helvetica,helv,sans-serif" size=1>
&copy; Copyright 1996&ndash;2021 StataCorp LLC
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/terms-of-use" class="bodylink">Terms of use</a>
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/privacy-policy" class="bodylink">Privacy</a>
&nbsp;&nbsp;&bull;&nbsp;&nbsp;
<a href="/company/contact" class="bodylink">Contact us</a>
</font>
</td>
</tr>
</table>
```

I wonder if this is also the cause of #321.

### PR DESCRIPTION
**Pull request by mcaceresb**
- [X] closes #389
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

Should be a straightforward fix.

### CODE REVIEW

**Review by kylebarron — APPROVED** [review]

**Comment by kylebarron** [comment]
We should probably push a new release to PyPI soon?

**Comment by kylebarron** [comment]
If you want PyPI publish access, you'd need to give me your PyPI username.

**Comment by mcaceresb** [comment]
@kylebarron Just made me an acct. `mcaceresb`

**Comment by kylebarron** [comment]
I added you as a maintainer to the pypi project. I should write up a doc for how to publish new versions. You should be able to update the website too if desired because you have push access to this repo (you'd just push to `gh-pages`).

**Comment by mcaceresb** [comment]
@kylebarron Never pushed to pypi but I'll try and figure it out at some point.

**Comment by kylebarron** [comment]
This is a busy week for me: big product release and then moving this weekend. If I haven't written a doc by next week, definitely @ me. It will be a lot simpler for me to write it down than for you to figure it out yourself.

**Comment by mcaceresb** [comment]
@kylebarron Ok; I'll @ you if I don't see sth next Friday.

**Comment by mcaceresb** [comment]
@kylebarron Hey! As promised I'm bugging you about how to push to pypi. No rush!

**Comment by kylebarron** [comment]
Sorry it's been a crazy two weeks... I was just about to sit down and write something, and I opened `CONTRIBUTING.md` and I already have some stuff there 😂. https://github.com/kylebarron/stata_kernel/blob/master/CONTRIBUTING.md#releasing-new-versions 

It's from two years ago but it all seems relevant. There are maybe a couple small things left out: 
- a reminder to update the changelog on a new release
- `pip install bumpversion` in the version number section

Otherwise seems good! Would you like to try following those instructions and publish a 1.13.0 and see if you have any issues?

**Comment by kylebarron** [comment]
> python setup.py sdist bdist_wheel

The `sdist` means "build a source distribution" and the `bdist_wheel` means "build a binary wheel". Since this package is pure python, it should be fine to only distribute the sdist, though I don't think also publishing the wheel hurts. You can see the last release I only pushed an sdist:

image

**Comment by mcaceresb** [comment]
@kylebarron Looks straightforward. Only wrinkle is the tests give me an error. Unsure what it's about:

```
$ pytest tests
==================================================================== test session starts ====================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/mauricio/Documents/projects/dev/code/stata_kernel
plugins: anyio-2.2.0
collected 241 items                                                                                                                                         

tests/test_kernel_completions.py s.ssssssss.s................ssssssssss.s                                                                             [ 16%]
tests/test_kernel_display_data.py ssssssssss.s..ssssssssssFs                                                                                          [ 27%]
tests/test_kernel_stdout.py ssssss.sss..s....ssssssssssFs                                                                                             [ 39%]
tests/test_mata_lexer.py ...................................................................                                                          [ 67%]
tests/test_stata_lexer.py ...............................................................................                                             [100%]

========================================================================= FAILURES ==========================================================================
_________________________________________________________ StataKernelTestFramework.test_kernel_info _________________________________________________________

self = <utils.StataKernelTestFramework testMethod=test_kernel_info>

    def test_kernel_info(self):
>       self.flush_channels()

/usr/lib/python3.9/site-packages/jupyter_kernel_test/__init__.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.9/site-packages/jupyter_kernel_test/__init__.py:30: in flush_channels
    msg = channel.get_msg(block=True, timeout=0.1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <jupyter_client.blocking.channels.ZMQSocketChannel object at 0x7f6be1676160>, block = True, timeout = 100.0

    def get_msg(self, block=True, timeout=None):
        """ Gets a message if there is one that is ready. """
        if block:
            if timeout is not None:
                timeout *= 1000  # seconds to ms
>           ready = self.socket.poll(timeout)
E           AttributeError: 'NoneType' object has no attribute 'poll'

/usr/lib/python3.9/site-packages/jupyter_client/blocking/channels.py:47: AttributeError
_________________________________________________________ StataKernelTestFramework.test_kernel_info _________________________________________________________

self = <utils.StataKernelTestFramework testMethod=test_kernel_info>

    def test_kernel_info(self):
>       self.flush_channels()

/usr/lib/python3.9/site-packages/jupyter_kernel_test/__init__.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.9/site-packages/jupyter_kernel_test/__init__.py:30: in flush_channels
    msg = channel.get_msg(block=True, timeout=0.1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <jupyter_client.blocking.channels.ZMQSocketChannel object at 0x7f6be1676160>, block = True, timeout = 100.0

    def get_msg(self, block=True, timeout=None):
        """ Gets a message if there is one that is ready. """
        if block:
            if timeout is not None:
                timeout *= 1000  # seconds to ms
>           ready = self.socket.poll(timeout)
E           AttributeError: 'NoneType' object has no attribute 'poll'

/usr/lib/python3.9/site-packages/jupyter_client/blocking/channels.py:47: AttributeError
===================================================================== warnings summary ======================================================================
../../../../../../../usr/lib/python3.9/site-packages/packaging/version.py:127: 2068 warnings
  /usr/lib/python3.9/site-packages/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
    warnings.warn(

../../../../../../../usr/lib/python3.9/site-packages/nose/importer.py:12
  /usr/lib/python3.9/site-packages/nose/importer.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import find_module, load_module, acquire_lock, release_lock

../../../../../../../usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:52
  /usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:52: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    payload = List(Dict)

../../../../../../../usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:59
  /usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:59: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    traceback = List(Unicode)

../../../../../../../usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:67
  /usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:67: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    args = List(Unicode)

../../../../../../../usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:78
  /usr/lib/python3.9/site-packages/jupyter_kernel_test/messagespec.py:78: DeprecationWarning: Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.
    matches = List(Unicode)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================== short test summary info ==================================================================
FAILED tests/test_kernel_display_data.py::StataKernelTestFramework::test_kernel_info - AttributeError: 'NoneType' object has no attribute 'poll'
FAILED tests/test_kernel_stdout.py::StataKernelTestFramework::test_kernel_info - AttributeError: 'NoneType' object has no attribute 'poll'
================================================= 2 failed, 175 passed, 64 skipped, 2073 warnings in 17.08s =================================================
```

**Comment by mcaceresb** [comment]
@kylebarron Ah, that didn't do it. I'll look into it a bit later, unless you reckon I ought to push w/o the tests. I'll see if I can look into Poetry as well (very cool name so my interest is piqued).

**Comment by kylebarron** [comment]
> unless you reckon I ought to push w/o the tests

Can you go back to the last release tag or two and see if the test is failing there too? If the test has been failing for a while, I'd say it's ok to push a new release still. If you go to the previous release and this test passes, then that's narrowed it down a bit more.x

**Comment by mcaceresb** [comment]
@kylebarron Mmm. Not 100% on why but the tests are getting stuck (they start running, there's some failures, and then it freezes). This wasn't happening before... Do you know if `pytest` changes some local files that might cause it to freeze/hang mid-test?

**Pull request merged**
