### PR TITLE
Use Pygments lexer to remove comments

### PR DESCRIPTION
**Pull request by kylebarron**
Fixes https://github.com/kylebarron/stata_kernel/issues/29

@mcaceresb

image

### CODE REVIEW

**Comment by mcaceresb** [comment]
The lexer is broken for me, atm. I think you are not joining back code chunks correctly? It seems each chunk is delimited by a space or a line break, but you are treating them as lines. At least for me, something like `disp "hi"` evaluates `disp` and then `"hi"`.

See [these lines](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/kernel.py#L270-L280). Your comment is not correct because `strip` also removes line breaks. Not sure that `strip(' ')` is required either, tho.

However, if you look at a `chunk` you will see a "word", not a line.

**Comment by mcaceresb** [comment]
This is what happens for me

```python
disp "hi"
"hi is not a valid command name
r(199);
```

**Comment by kylebarron** [comment]
On linux?

**Comment by mcaceresb** [comment]
Yes.

**Comment by kylebarron** [comment]
Can you try adding a space at the end

**Comment by mcaceresb** [comment]
Same.

**Pull request merged**
