### PR TITLE
[WIP] Code introspection.

### LINKED ISSUE #13: Code introspection

### PR DESCRIPTION
**Pull request by mcaceresb**
- [X] closes #13
- [ ] tests added / passed
- [X] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

One issue is that the kernel currently eats up sequential newlines, even if surrounded by non-blank output. This causes the formatting to be awkward. The help format would be fixed if the whitespace issue is fixed.

This displays plain text help even in atom. To fetch HTML help would slow-down introspection in other environments, but it's really easy to enable that; I recycled the code from `magic_help` so you can enable it if you want in `do_inspect`.

Last, this is also affected by the `--more--` bug in #103 because `help keyword` usually triggers more. The introspection would work correctly if that bug is fixed. The solution for now is to set more off before triggering introspection.

### CODE REVIEW

**Comment by kylebarron** [comment]
Tomorrow I'm taking a vacation until Sept 4. Once I get back I'll look at these PRs more closely.

**Comment by mcaceresb** [comment]
Bon voyage!

**Comment by kylebarron** [comment]
> One issue is that the kernel currently eats up sequential newlines, even if surrounded by non-blank output. This causes the formatting to be awkward. The help format would be fixed if the whitespace issue is fixed.

This should be fixed now.

> This displays plain text help even in atom. To fetch HTML help would slow-down introspection in other environments, but it's really easy to enable that; I recycled the code from magic_help so you can enable it if you want in do_inspect.

How does introspection work in qtconsole? It's just `?word`? I'm assuming the initial `?` isn't included in what Jupyter sends to the kernel? 

I personally think it's fine to enable HTML all the time.
This could be behind a setting, but these HTML files should be really small. Even `help syntax` is only 30KB, so should take a fraction of a second. If we implement basic ANSI-code formatting, having the HTML would help for that too.

> The solution for now is to set more off before triggering introspection.

I feel that it's probably best to always set more off.

**Comment by mcaceresb** [comment]
`(` triggers it.

My concern is not "response time given slow connection" rather "DNS lookup timeout time given the user is not connected to the internet." I'm good with the former bc, as you say, the files are small. The latter can take several seconds.

For something that is triggered as you type, it couod be somewhat frustrating.

**Comment by kylebarron** [comment]
Well introspection isn't triggered as you type in any frontend I don't think.

It's triggered by `?` in console plus an extra command option in Hydrogen I think

**Comment by mcaceresb** [comment]
`?` in the console just brings up the help, no?

It's triggered as you type in qtconsole by `(`; I don't think the HTML is working for me in hydrogen, but there is a slight lag in qtconsole so it's definitely trying to download something.

**Comment by kylebarron** [comment]
> ? in the console just brings up the help, no?

I thought that was _because_ of introspection. Maybe not

**Comment by mcaceresb** [comment]
[Here](https://github.com/kylebarron/stata_kernel/blob/master/stata_kernel/stata_magics.py#L232-L233)

**Pull request closed without merging**
