### PR TITLE
Removed deprecation

### PR DESCRIPTION
**Pull request by Mioroxi**
- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry
 replace=True

Just as the title says, it's a tiny edit that resolved an issue which stressed me out for 20 mins trying to find a workaround for. Everything else works as intended

### CODE REVIEW

**Comment by mcaceresb** [comment]
Sorry, what workaround is this for? That is, what is the issue that removing `replace=True` intending to fix?

**Comment by kylebarron** [comment]
Looks like this:
https://github.com/jupyter/jupyter_client/blob/44980c13680f4e4226cf25f199ce4e4bb6e11296/jupyter_client/kernelspec.py#L326-L331

The user probably sees the deprecation notice upon installing

**Comment by Mioroxi** [comment]
I got drunk as fuck and started doing shit, my bad.
That isn't what the workaround was for, since the program didn't install at all for me. I got a deprecation warning as well as a long list of python compile execute errors when I ran the installer, and then I narrowed down the problem to install.py. 
All I remember is that after removing replace=True I've had no issues whatsoever.
Sorry again for the awkwardness

**Comment by kylebarron** [comment]
Given the deprecation warning, I'm happy to merge this @mcaceresb . Any thoughts?

**Pull request merged**
