### PR TITLE
Fix more

### LINKED ISSUE #103: more woes
#### Code Sample

```stata
more
```
#### Problem description

`more` crashes the kernel.

#### Expected Output

No crash.

#### Debugging log

From `tail`

```
. more
`addec426932e71323700afa1911f8f1c'
more
        
. addec426932e71323700afa1911f8f1c'
command addec426932e71323700afa1911f8f1c is unrecognized
r(199);
```

#### Package Version

```
Name: stata-kernel
Version: 1.3.1
Summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
Home-page: https://github.com/kylebarron/stata_kernel
Author: Kyle Barron
Author-email: barronk@mit.edu
License: GPLv3
Location: /usr/lib/python3.6/site-packages
Requires: beautifulsoup4, jupyter-client, IPython, ipykernel, pandas, pillow, pexpect, pygments, regex
Required-by: 
```

### PR DESCRIPTION
**Pull request by kylebarron**
- [x] closes #103
- [ ] tests added / passed
- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [ ] whatsnew entry

### CODE REVIEW

**Comment by mcaceresb** [comment]
Does codemirror show up in the code?

**Comment by kylebarron** [comment]
What do you mean?

**Comment by mcaceresb** [comment]
````
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/stata_kernel/__main__.py", line 4, in <module>
    IPKernelApp.launch_instance(kernel_class=StataKernel)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 465, in initialize
    self.init_kernel()
  File "/usr/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 376, in init_kernel
    user_ns=self.user_ns,
  File "/usr/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/stata_kernel/kernel.py", line 54, in __init__
    to_path.parents[0].mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.6/pathlib.py", line 1246, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/notebook/static/components/codemirror/mode/stata'
```

The folder does not exist on my system. I haven't seen that error before. Maybe it's an issue on my end.

**Comment by kylebarron** [comment]
Ah shoot. I need to wrap that in a try/except. That's trying to copy the Codemirror js file to the Jupyter notebook package to highlight Jupyter notebook

**Comment by mcaceresb** [comment]
I don't think it's my system. I can load it on other branches. I just get this issue in the dev-more branch.

**Comment by kylebarron** [comment]
Other branches aren't as updated. I assume if you try master it will fail the same

**Comment by mcaceresb** [comment]
Yes... Very odd. I need root for that folder. Not sure what this is doing post-install.

**Comment by kylebarron** [comment]
So in 1.5.0 I added syntax highlighting support for Pygments and Codemirror, but in order to do that without waiting for those packages to be updated, I just try to copy the syntax highlighting files to the dirs they would reside in. I set it so that every time the kernel starts, it checks the timestamps on each.

I just updated master and this branch with a try/except for the copy operation.

**Comment by mcaceresb** [comment]
Not 100% why this is necessary outside the install, but I'll try again.

**Comment by mcaceresb** [comment]
Cool. Seems to be working.

**Comment by kylebarron** [comment]
Well the idea is that `install.py` only ever gets run once. So 1) the people who have already downloaded the kernel would never see it and 2) if I make updates to the syntax highlighting files, and people do `pip --upgrade`, I want people to see them without running `install.py` again.

**Pull request merged**
